export const Strings = {
  app_name: 'Coffee App',
  title: 'Coffee so good, your taste buds will love it.',
  sub_title: 'The best grain, the finest roast, the powerfull flavour',
  get_started: 'Get Started',
  location: 'Location',
  search_coffee: 'Search Coffee',
  promo: 'Promo',
  promo_text: 'Buy One, Get One FREE',
  details: 'Details',
  description: 'Description',
  size: 'Size',
  order: 'Order',
  read_more: 'Read More',
  price: 'Price',
  buy_now: 'Buy Now',
  deliver: 'Deliver',
  pick_up: 'Pick Up',
  edit_address: 'Edit Address',
  add_note: 'Add Note',
  discount_applied: 'Discount Applied',
  payment_summary: 'Payment Summary',
  delivery_fee: 'Delivery Fee',
  total_payment: 'Total Payment',
  cash: 'Cash',
};
